name: Update currency change daily
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Get exchange rate
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          RESPONSE=$(curl -s https://api.apis.net.pe/v1/tipo-cambio-sunat)

          COMPRA=$(echo "$RESPONSE" | jq -r '.compra')
          VENTA=$(echo "$RESPONSE" | jq -r '.venta')

          echo "COMPRA=$COMPRA" >> $GITHUB_ENV
          echo "VENTA=$VENTA" >> $GITHUB_ENV

      - name: Insert into Supabase
        run: |
            curl --fail --show-error --silent \
                -X POST "${{ secrets.SUPABASE_URL }}/rest/v1/finanzas_tipos_cambio" \
                -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
                -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
                -H "Content-Type: application/json" \
                -H "Prefer: resolution=merge-duplicates" \
                -d "{
                    \"moneda\": \"USD\",
                    \"moneda_destino\": \"PEN\",
                    \"compra\": ${COMPRA},
                    \"venta\": ${VENTA},
                    \"fuente\": \"SUNAT\"
                }"
